language: node_js
node_js:
- '0.10'
deploy:
  provider: openshift
  user: aleksuei.riabtsev@ec.gc.ca
  password:
    secure: P4tbpmVJUvpxq2YzwJg0U+PDbu1gBVChVTR0eQYbcJL4qY9QFn9LZA29OafiuEwT4ACQOjnpJ79UfWDvWF8iGVOy6B3reMqJ6zPkiyJN7eI9lMYZz9SR+4fuh/1cNTU6TZChZrwFPqp7qIjkvEdTp7c6WcIRncmqi6w2WK5iiDcKtbPvs1gmuWLvsVINaVB8hUOcmNV0Ecg76Jz4GFDKSFzeFr7BFPmX6H92YreLfNSJcsOCmOg8YdTHOLIAxMR4eKaf+fMI8la8+EXjSOUTHd0RCBXXLQitl4+cxTfxdFPUMTAS9nZQ7QWWTCkcacpdhDwi6w+Sx+PC/7a2NDKdhNviQ7pyW3D8W4IwrqBCw8E4AOO6sVat0WZuRdmcO2lgVaPaJ0cBtGaOS9BdAmgGWAkmQK/o7yg75wN8QR8kKe70ln7Or0CRZg7GrRnyveV0D3UMbYPPpoc5+flG2joafLhZnTiIi/bvcW31qC5Xynh+E0LeChkVXDuFnHi+65ajxce8udFw8ILqsE2A+zwuG15aHisynZObJA4rzgZjlEFC+rQmpJvl/QDyGqOTzsAtrb6BQclv+UG+Yct0oFxMtPYvK1+P7IAtDP23D6FRss1XnIcHbui1NVZdrAW4rTrj18vF8Vbhg7ydBUEyY1Uz230ljzLBfuN/G1bnubwcOJ8=
  app: hutest
  domain: volkit
  on:
    repo: AleksueiR/glitch
    branch: heads/ar/redis
