language: node_js
node_js:
- '0.10'
deploy:
  provider: openshift
  user: aleksuei.riabtsev@ec.gc.ca
  password:
    secure: ***REMOVED***
  app: hutest
  domain: volkit
  on:
    repo: AleksueiR/glitch
    branch: master
