language: node_js
node_js:
- '0.10'
deploy:
  provider: openshift
  user: aleksuei.riabtsev@ec.gc.ca
  password:
    secure: WUeCtZKM+986xXCVwK2S8hhTzyyX0Vxkqehv1x8+Aqc/5KKZaZupq+UG5SYH3Pp/O1/0qjDFvIxG5SeDAFTAQL1SdIdsRqtmtpn4EO5ciMPuTLa2CmBiA3VfUSs85RgfT0waggvq/P5qNUFqEYgBI16K9DQpPAxj8EZ7RUFOsZ9lee1U6qgDbBknwueRIFcCMhQA/ZebowUQCsKQJt0Lr9zBjw/wSNJkFrpseV7HpvgtAsMhMkSezCS1KFqdbHv2GmA6/o7JafiY+BB6mwmHVC0fjK/IqMnPEHHGtNfV7HuEYKJEVqjOEen62o/bWXuBdlAGfDj6rHL9vKw/JO60Vrx7xe79eZEO9CH6aMvdZPpH3b/tb+Zc53qB3fdGdks5dZzuG0Erj3eYVRiXZF8sSsJ54CwJXU8uc+v+h1H9ipinOjWaz+/aU59dM6c0HP+ioiJoP9IxENhqITcfx6mpatNfMux4xpP62TaCOEbBLPrz1PA6E2Pf+KH0eY1Kjmbmk0t5jNo4ZnunQqiHPJtjYtvysOT3rfr+QW7fUv/Jjfa8ahGSHF7QH/uc9NUdxzqtakztXjI8XtIN3EymWO8tLLFWwKuWHZAsBEf+TdA8O7vO8brnuDKCrW35Lu62YLzDK8h3z5pBFsetCLXSb1RGhH/VDRwUBEEtypNEbKG4RDU=
  app: hutest
  domain: volkit
  on:
    branch: redis
